sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 6.0.0
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag book-management-db:latest $DOCKER_USERNAME/book-management-db:$TRAVIS_JOB_ID;
    docker tag book-management-api:latest $DOCKER_USERNAME/book-management-api:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/book-management-db;
    docker push $DOCKER_USERNAME/book-management-api;
  on:
    branch: master
notifications:
  email: false