# docker-compose up
# https://localhost:5001/swagger

version: '3.4'

services:
  db:
    image: book-management-db
    build:
      context: .
      dockerfile: BookManagement.API/Db.Dockerfile
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: my1Strong2Key3
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
    networks:
      - my-network

  api:
    image: book-management-api
    build:
      context: .
      dockerfile: BookManagement.API/App.Dockerfile
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
